server:
  port: 8761
eureka:
  environment: dev
  datacenter: chengdu
  instance:
    hostname: eureka-chengdu
    appname: eureka-server
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-hangzhou:8762/eureka/
  #server:
    #关闭自我保护机制，保证不可用服务被及时踢除
    #enable-self-preservation: false
    #eviction-interval-timer-in-ms: 2000