server:
  port: 8762
eureka:
  environment: dev
  datacenter: hangzhou
  instance:
    hostname: eureka-hangzhou
    appname: eureka-server
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-chengdu:8761/eureka/
    #server:
    #关闭自我保护机制，保证不可用服务被及时踢除
    #enable-self-preservation: false
    #eviction-interval-timer-in-ms: 2000