spring:
  application:
    name: business
server:
  port: 7800
  eureka:
    instance:
      prefer-ip-address: true #以IP形式注册
    client:
      register-with-eureka: true # 是否注册自己的信息到EurekaServer，默认是true
      fetch-registry: true # 是否拉取其它服务的信息，默认是true
      service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
        defaultZone: http://eureka-server1.v1.cmcc:8761/eureka,http://eureka-server2.v1.cmcc:8762/eureka

seata:
  enabled: true
  # 事务群组（可以每个应用独立取名，也可以使用相同的名字）
  tx-service-group: my_tx_group
  client:
    rm-report-success-enable: true
    # 异步提交缓存队列长度（默认10000）
    rm-async-commit-buffer-limit: 1000
    # 一阶段全局提交结果上报TC重试次数（默认1次，建议大于1）
    tm-commit-retry-count:   3
    # 一阶段全局回滚结果上报TC重试次数（默认1次，建议大于1）
    tm-rollback-retry-count: 3
    support:
      # 数据源自动代理开关（默认false关闭）
      spring-datasource-autoproxy: true
  service:
    vgroup-mapping:
      my_tx_group: seata-server
    grouplist:
      default: seata-server:8091
  registry:
    type: eureka
    eureka:
      serviceUrl: http://eureka-chengdu:8761/eureka/,http://eureka-hangzhou:8762/eureka/